# Generated by Django 5.1.1 on 2024-10-13 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrops', '0002_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_login',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
